"""initial_schema

Revision ID: bcecf6fff2ab
Revises:
Create Date: 2026-08-01 17:29:56.665446+00:00

"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bcecf6fff2ab"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "political_party",
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("abbreviation", sa.String(length=30), nullable=True),
        sa.Column("eci_id", sa.String(length=50), nullable=True),
        sa.Column("symbol_url", sa.String(length=500), nullable=True),
        sa.Column("is_national_party", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("eci_id"),
    )
    op.create_index(op.f("ix_political_party_slug"), "political_party", ["slug"], unique=True)
    op.create_table(
        "politician",
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("name_hindi", sa.String(length=300), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column(
            "gender",
            sa.Enum("MALE", "FEMALE", "OTHER", "UNDISCLOSED", name="gender_enum"),
            nullable=False,
        ),
        sa.Column("photo_url", sa.String(length=500), nullable=True),
        sa.Column("official_website", sa.String(length=500), nullable=True),
        sa.Column("eci_candidate_id", sa.String(length=50), nullable=True),
        sa.Column("pan_hash", sa.String(length=64), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("eci_candidate_id"),
    )
    op.create_index(op.f("ix_politician_name"), "politician", ["name"], unique=False)
    op.create_index(op.f("ix_politician_slug"), "politician", ["slug"], unique=True)
    op.create_table(
        "source_provider",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("short_code", sa.String(length=30), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "is_official",
            sa.Boolean(),
            nullable=False,
            comment="True = government or quasi-government source",
        ),
        sa.Column("request_delay_seconds", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("short_code"),
    )
    op.create_table(
        "state",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("iso_code", sa.String(length=10), nullable=False),
        sa.Column("is_union_territory", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("iso_code"),
    )
    op.create_index(op.f("ix_state_slug"), "state", ["slug"], unique=True)
    op.create_table(
        "audit_log",
        sa.Column("actor", sa.String(length=200), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("politician_id", sa.UUID(), nullable=True),
        sa.Column("target_table", sa.String(length=100), nullable=True),
        sa.Column("target_id", sa.String(length=100), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=50), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["politician_id"], ["politician.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_log_politician_id"), "audit_log", ["politician_id"], unique=False
    )
    op.create_table(
        "constituency",
        sa.Column("state_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "constituency_type",
            sa.Enum("LOK_SABHA", "VIDHAN_SABHA", "RAJYA_SABHA", name="constituency_type_enum"),
            nullable=False,
        ),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("reserved_category", sa.String(length=50), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["state_id"], ["state.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_constituency_slug"), "constituency", ["slug"], unique=True)
    op.create_table(
        "correction_request",
        sa.Column("politician_id", sa.UUID(), nullable=True),
        sa.Column("submitter_name", sa.String(length=200), nullable=True),
        sa.Column("submitter_email", sa.String(length=200), nullable=True),
        sa.Column("field_name", sa.String(length=200), nullable=False),
        sa.Column("current_value", sa.Text(), nullable=True),
        sa.Column("claimed_correct_value", sa.Text(), nullable=False),
        sa.Column("evidence_url", sa.String(length=500), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "UNDER_REVIEW",
                "APPROVED",
                "REJECTED",
                "WITHDRAWN",
                name="correction_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("reviewer_notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["politician_id"], ["politician.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_correction_request_politician_id"),
        "correction_request",
        ["politician_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_correction_request_status"), "correction_request", ["status"], unique=False
    )
    op.create_table(
        "grade_snapshot",
        sa.Column("politician_id", sa.UUID(), nullable=False),
        sa.Column(
            "overall_grade",
            sa.Enum("A", "B", "C", "D", "F", "NA", name="grade_letter_enum"),
            nullable=False,
        ),
        sa.Column("overall_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("engine_version", sa.String(length=50), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["politician_id"], ["politician.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_grade_snapshot_politician_id"), "grade_snapshot", ["politician_id"], unique=False
    )
    op.create_table(
        "party_membership",
        sa.Column("politician_id", sa.UUID(), nullable=False),
        sa.Column("party_id", sa.UUID(), nullable=False),
        sa.Column("from_date", sa.Date(), nullable=False),
        sa.Column("to_date", sa.Date(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["party_id"], ["political_party.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["politician_id"], ["politician.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_party_membership_politician_id"),
        "party_membership",
        ["politician_id"],
        unique=False,
    )
    op.create_table(
        "politician_alias",
        sa.Column("politician_id", sa.UUID(), nullable=False),
        sa.Column("alias", sa.String(length=300), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["politician_id"], ["politician.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_politician_alias_alias"), "politician_alias", ["alias"], unique=False)
    op.create_index(
        op.f("ix_politician_alias_politician_id"),
        "politician_alias",
        ["politician_id"],
        unique=False,
    )
    op.create_table(
        "source_snapshot",
        sa.Column("provider_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column(
            "url_hash", sa.String(length=64), nullable=False, comment="SHA-256 of normalised URL"
        ),
        sa.Column(
            "content_hash",
            sa.String(length=64),
            nullable=False,
            comment="SHA-256 of raw response body",
        ),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column(
            "parser_version",
            sa.String(length=50),
            nullable=False,
            comment="Semantic version of the parser used",
        ),
        sa.Column("raw_content_size_bytes", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["provider_id"], ["source_provider.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url_hash", "content_hash", name="uq_snapshot_url_content"),
    )
    op.create_index(
        op.f("ix_source_snapshot_provider_id"), "source_snapshot", ["provider_id"], unique=False
    )
    op.create_index(
        op.f("ix_source_snapshot_url_hash"), "source_snapshot", ["url_hash"], unique=False
    )
    op.create_table(
        "correction_history",
        sa.Column("correction_request_id", sa.UUID(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "PENDING",
                "UNDER_REVIEW",
                "APPROVED",
                "REJECTED",
                "WITHDRAWN",
                name="correction_status_enum",
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "PENDING",
                "UNDER_REVIEW",
                "APPROVED",
                "REJECTED",
                "WITHDRAWN",
                name="correction_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("changed_by", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["correction_request_id"], ["correction_request.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_correction_history_correction_request_id"),
        "correction_history",
        ["correction_request_id"],
        unique=False,
    )
    op.create_table(
        "election",
        sa.Column("constituency_id", sa.UUID(), nullable=False),
        sa.Column(
            "election_type",
            sa.Enum("GENERAL", "ASSEMBLY", "BY_ELECTION", "RAJYA_SABHA", name="election_type_enum"),
            nullable=False,
        ),
        sa.Column("election_date", sa.Date(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("phase", sa.Integer(), nullable=True),
        sa.Column("total_voters", sa.Integer(), nullable=True),
        sa.Column("total_votes_polled", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["constituency_id"], ["constituency.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_election_constituency_id"), "election", ["constituency_id"], unique=False
    )
    op.create_index(op.f("ix_election_year"), "election", ["year"], unique=False)
    op.create_table(
        "grade_metric_result",
        sa.Column("grade_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("metric_name", sa.String(length=100), nullable=False),
        sa.Column("raw_value", sa.Text(), nullable=True),
        sa.Column(
            "grade",
            sa.Enum("A", "B", "C", "D", "F", "NA", name="grade_letter_enum"),
            nullable=False,
        ),
        sa.Column("score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("weight", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "confidence",
            sa.Enum(
                "OFFICIAL_PRIMARY",
                "OFFICIAL_SECONDARY",
                "INFERRED_DERIVED",
                "USER_SUBMITTED",
                name="confidence_enum",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["grade_snapshot_id"], ["grade_snapshot.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_grade_metric_result_grade_snapshot_id"),
        "grade_metric_result",
        ["grade_snapshot_id"],
        unique=False,
    )
    op.create_table(
        "legislative_term",
        sa.Column("politician_id", sa.UUID(), nullable=False),
        sa.Column("constituency_id", sa.UUID(), nullable=True),
        sa.Column(
            "house",
            sa.Enum(
                "LOK_SABHA", "RAJYA_SABHA", "VIDHAN_SABHA", "VIDHAN_PARISHAD", name="house_enum"
            ),
            nullable=False,
        ),
        sa.Column("from_date", sa.Date(), nullable=False),
        sa.Column("to_date", sa.Date(), nullable=True),
        sa.Column("lok_sabha_number", sa.Integer(), nullable=True),
        sa.Column("state_represented", sa.String(length=100), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["constituency_id"], ["constituency.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["politician_id"], ["politician.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_legislative_term_politician_id"),
        "legislative_term",
        ["politician_id"],
        unique=False,
    )
    op.create_table(
        "attendance_record",
        sa.Column("legislative_term_id", sa.UUID(), nullable=False),
        sa.Column("source_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("session_name", sa.String(length=100), nullable=False),
        sa.Column("session_year", sa.Integer(), nullable=False),
        sa.Column("days_present", sa.Integer(), nullable=False),
        sa.Column("days_total", sa.Integer(), nullable=False),
        sa.Column("attendance_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["legislative_term_id"], ["legislative_term.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"], ["source_snapshot.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attendance_record_legislative_term_id"),
        "attendance_record",
        ["legislative_term_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_record_session_year"),
        "attendance_record",
        ["session_year"],
        unique=False,
    )
    op.create_table(
        "election_result",
        sa.Column("election_id", sa.UUID(), nullable=False),
        sa.Column("politician_id", sa.UUID(), nullable=False),
        sa.Column("party_id", sa.UUID(), nullable=True),
        sa.Column("votes", sa.Integer(), nullable=True),
        sa.Column("vote_share_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("won", sa.Boolean(), nullable=False),
        sa.Column("runner_up", sa.Boolean(), nullable=False),
        sa.Column("margin", sa.Integer(), nullable=True),
        sa.Column("eci_form26_url", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["election_id"], ["election.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["party_id"], ["political_party.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["politician_id"], ["politician.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_election_result_election_id"), "election_result", ["election_id"], unique=False
    )
    op.create_index(
        op.f("ix_election_result_politician_id"), "election_result", ["politician_id"], unique=False
    )
    op.create_table(
        "legislative_activity",
        sa.Column("legislative_term_id", sa.UUID(), nullable=False),
        sa.Column("source_snapshot_id", sa.UUID(), nullable=False),
        sa.Column(
            "activity_type",
            sa.Enum(
                "STARRED_QUESTION",
                "UNSTARRED_QUESTION",
                "PRIVATE_MEMBER_BILL",
                "DEBATE_PARTICIPATION",
                "ZERO_HOUR",
                "CALLING_ATTENTION",
                "SHORT_DURATION_DISCUSSION",
                name="activity_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("activity_date", sa.Date(), nullable=True),
        sa.Column("session_name", sa.String(length=100), nullable=True),
        sa.Column("ministry_concerned", sa.String(length=200), nullable=True),
        sa.Column("is_admitted", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["legislative_term_id"], ["legislative_term.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"], ["source_snapshot.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_legislative_activity_activity_type"),
        "legislative_activity",
        ["activity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legislative_activity_legislative_term_id"),
        "legislative_activity",
        ["legislative_term_id"],
        unique=False,
    )
    op.create_table(
        "affidavit",
        sa.Column("election_result_id", sa.UUID(), nullable=False),
        sa.Column("source_snapshot_id", sa.UUID(), nullable=False),
        sa.Column("filing_date", sa.Date(), nullable=True),
        sa.Column("affidavit_url", sa.String(length=500), nullable=True),
        sa.Column("is_revised", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["election_result_id"], ["election_result.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"], ["source_snapshot.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_affidavit_election_result_id"), "affidavit", ["election_result_id"], unique=False
    )
    op.create_table(
        "affidavit_entry",
        sa.Column("affidavit_id", sa.UUID(), nullable=False),
        sa.Column(
            "source_snapshot_id",
            sa.UUID(),
            nullable=False,
            comment="Source required — no unsourced entries permitted",
        ),
        sa.Column(
            "field_name",
            sa.String(length=100),
            nullable=False,
            comment="e.g. 'total_assets', 'educational_qualification'",
        ),
        sa.Column("field_value", sa.Text(), nullable=True),
        sa.Column(
            "raw_value", sa.Text(), nullable=True, comment="Unparsed string from source document"
        ),
        sa.Column(
            "section", sa.String(length=100), nullable=True, comment="Section of the affidavit form"
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["affidavit_id"], ["affidavit.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"], ["source_snapshot.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_affidavit_entry_affidavit_id"), "affidavit_entry", ["affidavit_id"], unique=False
    )
    op.create_table(
        "asset_declaration",
        sa.Column("affidavit_entry_id", sa.UUID(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "IMMOVABLE",
                "MOVABLE",
                "FINANCIAL",
                "LIABILITY",
                "OTHER",
                name="asset_category_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "ownership",
            sa.Enum("SELF", "SPOUSE", "DEPENDENT", "HUF", "OTHER", name="asset_ownership_enum"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("value_inr", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("raw_value_text", sa.String(length=200), nullable=True),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["affidavit_entry_id"], ["affidavit_entry.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_asset_declaration_affidavit_entry_id"),
        "asset_declaration",
        ["affidavit_entry_id"],
        unique=False,
    )
    op.create_table(
        "criminal_case",
        sa.Column("affidavit_entry_id", sa.UUID(), nullable=False),
        sa.Column("case_number", sa.String(length=200), nullable=True),
        sa.Column("court", sa.String(length=300), nullable=True),
        sa.Column("section_of_law", sa.Text(), nullable=True),
        sa.Column("offence_description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CHARGE_FRAMED",
                "CONVICTED",
                "ACQUITTED",
                "DISCHARGED",
                "COMPOUNDED",
                "UNKNOWN",
                name="case_status_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("HEINOUS", "SERIOUS", "MINOR", "UNKNOWN", name="case_severity_enum"),
            nullable=False,
        ),
        sa.Column("year_filed", sa.Integer(), nullable=True),
        sa.Column("is_cognizable", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["affidavit_entry_id"], ["affidavit_entry.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_criminal_case_affidavit_entry_id"),
        "criminal_case",
        ["affidavit_entry_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_criminal_case_affidavit_entry_id"), table_name="criminal_case")
    op.drop_table("criminal_case")
    op.drop_index(op.f("ix_asset_declaration_affidavit_entry_id"), table_name="asset_declaration")
    op.drop_table("asset_declaration")
    op.drop_index(op.f("ix_affidavit_entry_affidavit_id"), table_name="affidavit_entry")
    op.drop_table("affidavit_entry")
    op.drop_index(op.f("ix_affidavit_election_result_id"), table_name="affidavit")
    op.drop_table("affidavit")
    op.drop_index(
        op.f("ix_legislative_activity_legislative_term_id"), table_name="legislative_activity"
    )
    op.drop_index(op.f("ix_legislative_activity_activity_type"), table_name="legislative_activity")
    op.drop_table("legislative_activity")
    op.drop_index(op.f("ix_election_result_politician_id"), table_name="election_result")
    op.drop_index(op.f("ix_election_result_election_id"), table_name="election_result")
    op.drop_table("election_result")
    op.drop_index(op.f("ix_attendance_record_session_year"), table_name="attendance_record")
    op.drop_index(op.f("ix_attendance_record_legislative_term_id"), table_name="attendance_record")
    op.drop_table("attendance_record")
    op.drop_index(op.f("ix_legislative_term_politician_id"), table_name="legislative_term")
    op.drop_table("legislative_term")
    op.drop_index(
        op.f("ix_grade_metric_result_grade_snapshot_id"), table_name="grade_metric_result"
    )
    op.drop_table("grade_metric_result")
    op.drop_index(op.f("ix_election_year"), table_name="election")
    op.drop_index(op.f("ix_election_constituency_id"), table_name="election")
    op.drop_table("election")
    op.drop_index(
        op.f("ix_correction_history_correction_request_id"), table_name="correction_history"
    )
    op.drop_table("correction_history")
    op.drop_index(op.f("ix_source_snapshot_url_hash"), table_name="source_snapshot")
    op.drop_index(op.f("ix_source_snapshot_provider_id"), table_name="source_snapshot")
    op.drop_table("source_snapshot")
    op.drop_index(op.f("ix_politician_alias_politician_id"), table_name="politician_alias")
    op.drop_index(op.f("ix_politician_alias_alias"), table_name="politician_alias")
    op.drop_table("politician_alias")
    op.drop_index(op.f("ix_party_membership_politician_id"), table_name="party_membership")
    op.drop_table("party_membership")
    op.drop_index(op.f("ix_grade_snapshot_politician_id"), table_name="grade_snapshot")
    op.drop_table("grade_snapshot")
    op.drop_index(op.f("ix_correction_request_status"), table_name="correction_request")
    op.drop_index(op.f("ix_correction_request_politician_id"), table_name="correction_request")
    op.drop_table("correction_request")
    op.drop_index(op.f("ix_constituency_slug"), table_name="constituency")
    op.drop_table("constituency")
    op.drop_index(op.f("ix_audit_log_politician_id"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_state_slug"), table_name="state")
    op.drop_table("state")
    op.drop_table("source_provider")
    op.drop_index(op.f("ix_politician_slug"), table_name="politician")
    op.drop_index(op.f("ix_politician_name"), table_name="politician")
    op.drop_table("politician")
    op.drop_index(op.f("ix_political_party_slug"), table_name="political_party")
    op.drop_table("political_party")
    # ### end Alembic commands ###
